services:
  api:
    build:
      context: ../backend
      dockerfile: Dockerfile
    env_file:
      - ../backend/.env
    container_name: private-rag-api
    ports:
      - "8000:8000"
    environment:
      APP_ENV: development
      DATABASE_URL: postgresql://rag_user:rag_password@db:5432/private_rag
      STORAGE_DIR: /app/storage
      OLLAMA_BASE_URL: http://ollama:11434
      EMBEDDING_MODEL: nomic-embed-text
      GENERATION_MODEL: llama3.2:1b
      RETRIEVAL_MAX_DISTANCE: 0.32
    volumes:
      - private_rag_storage:/app/storage
    depends_on:
      - db
      - ollama

  db:
    image: pgvector/pgvector:pg16-trixie
    container_name: private-rag-db
    environment:
      POSTGRES_USER: rag_user
      POSTGRES_PASSWORD: rag_password
      POSTGRES_DB: private_rag
    ports:
      - "5432:5432"
    volumes:
      - private_rag_pgdata:/var/lib/postgresql/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql

  ollama:
    image: ollama/ollama:latest
    container_name: private-rag-ollama
    ports:
      - "11434:11434"
    volumes:
      - private_rag_ollama:/root/.ollama

volumes:
  private_rag_pgdata:
  private_rag_storage:
  private_rag_ollama: